# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b911dbd453997e80f77588c931641fdaf538e68ce55a0b0c38332e1e84f1f7d210d8f026c7f5f6ecc8be2333dbce0562531d716297e89cca6033971c21ee4b80

test:
  secret_key_base: f29c3a223d3220588d005c9e305864c23bd1ab248680f07ad3b25ff98c59ba59bf6ea531fa517da8ec604b5910c8be81b810c079ca539b090dbbdfc3a34c3102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
